import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Belajar NextJS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const router = useRouter();
  const handleClick = (url) => {
    router.push(url)
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>Header - Layout rooter</div>
        <ul>
          <li><Link href={'/'}>Home</Link></li>
          <li><Link href={'/dashboard-app'}>Dashboard App</Link></li>
          <li><Link href={'/settings-app'}>Settings</Link></li>
          <li><Link href={'/user-app'}>User App</Link></li>
          <li><Link href={'/dashboard'}>Dashboard</Link></li>
        </ul>

        {children}
        <div>Footer Layout rooter</div>
        </body>
    </html>
  )
}
