import React from 'react';

// import { Container } from './styles';
export const metadata = {
  title: 'Settings app',
  description: 'Generated by create next app',
}
function SettingApps() {
  return <>
  <h1>Settings Apps</h1>
  </>;
}

export default SettingApps;