import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard app",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return <div style={{ backgroundColor: "red" }}>{children}</div>;
}
